version: 1.0.{build}
image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: ToDo_sha.sln

test_script:
  - cd Tests
  - dotnet test
